apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
        - name: loadbalancer
          image: loadbalancer:latest
          imagePullPolicy: Never
          env:
            - name: TARGET_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: lb-config
                  key: target_servers
